# Data Management

Contents

    Appending Data
    Applying Functions Across Data Elements

Here we look at some common tasks that come up when dealing with data. These tasks range from assembling different data sets into more convenient forms and ways to apply functions to different parts of the data sets. The topics in this section demonstrate some of the power of R, but it may not be clear at first. The functions are commonly used in a wide variety of circumstances for a number of different reasons. These tools have saved me a great deal of time and effort in circumstances that I would not have predicted in advance.

The important thing to note, though, is that this section is called “Data Management.” It is not called “Data Manipulation.” Politicians “manipulate” data, we “manage” them.

# Appending Data

When you have more than one set of data you may want to bring them together. You can bring different data sets together by appending as rows (rbind) or by appending as columns (cbind). The first example shows how this done with two data frames. The arguments to the functions can take any number of objects. We only use two here to keep the demonstration simpler, but additional data frames can be appended in the same call. It is important to note that when you bring things together as rows the names of the objects within the data frame must be the same.

In [1]:
a <- data.frame(one=c( 0, 1, 2),two=c("a","a","b"))
b <- data.frame(one=c(10,11,12),two=c("c","c","d"))

In [2]:
a
b

one two
1 0   a  
2 1   a  
3 2   b

one two
1 10  c  
2 11  c  
3 12  d

In [6]:
v <- rbind(a,b)
w <- cbind(a,b)
typeof(v)
typeof(w)
v
w

[1] "list"

[1] "list"

one two
1  0  a  
2  1  a  
3  2  b  
4 10  c  
5 11  c  
6 12  d

one two one two
1 0   a   10  c  
2 1   a   11  c  
3 2   b   12  d

In [7]:
names(w) = c("one","two","three","four")
w

one two three four
1 0   a   10    c   
2 1   a   11    c   
3 2   b   12    d

The same commands also work with vectors and matrices and behave in a similar manner.

In [8]:
A = matrix(c( 1, 2, 3, 4, 5, 6),ncol=3,byrow=TRUE)
A

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [9]:
B = matrix(c(10,20,30,40,50,60),ncol=3,byrow=TRUE)
B

[,1] [,2] [,3]
[1,] 10   20   30  
[2,] 40   50   60

In [11]:
V <- rbind(A,B)
typeof(V)
V

[1] "double"

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,] 10   20   30  
[4,] 40   50   60

In [12]:
W <- cbind(A,B)
typeof(W)
W

[1] "double"

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    2    3    10   20   30  
[2,] 4    5    6    40   50   60

## Applying Functions Across Data Elements

The various apply functions can be an invaluable tool when trying to work with subsets within a data set. The different versions of the apply commands are used to take a function and have the function perform an operation on each part of the data. There are a wide variety of these commands, but we only look at two sets of them. The first set, lapply and sapply, is used to apply a function to every element in a list. The second one, tapply, is used to apply a function on each set broken up by a given set of factors.
### Operations on Lists and Vectors

First, the lapply command is used to take a list of items and perform some function on each member of the list. That is, the list includes a number of different objects. You want to perform some operation on every object within the list. You can use lapply to tell R to go through each item in the list and perform the desired action on each item.

In the following example a list is created with three elements. The first is a randomly generated set of numbers with a normal distribution. The second is a randomly generated set of numbers with an exponential distribution. The last is a set of factors. A summary is then performed on each element in the list.

In [13]:
x <- list(a=rnorm(200,mean=1,sd=10),
            b=rexp(300,10.0),
            c=as.factor(c("a","b","b","b","c","c")))
lapply(x,summary)

$a
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-26.0941  -6.0585   1.6341   0.9526   7.7410  25.0305 

$b
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
0.0009762 0.0279467 0.0728680 0.0965922 0.1358865 0.5708499 

$c
a b c 
1 3 2 


The lapply command returns a list. The entries in the list have the same names as the entries in the list that is passed to it. The values of each entry are the results from applying the function. The sapply function is similar, but the difference is that it tries to turn the result into a vector or matrix if possible. If it does not make sense then it returns a list just like the lapply command.

In [14]:
x <- list(a=rnorm(8,mean=1,sd=10),b=rexp(10,10.0))
x

$a
[1]   1.5839805 -10.7943015   2.0237966  -0.5141318   0.5368041  15.5906332
[7]  11.0231893   2.0388666

$b
 [1] 0.010345085 0.112420039 0.015214973 0.019495580 0.004884674 0.089703680
 [7] 0.044977700 0.043858885 0.328673537 0.061697497

In [15]:
val <- lapply(x,mean)
typeof(val)
val

[1] "list"

$a
[1] 2.686105

$b
[1] 0.07312717

In [16]:
val$a

[1] 2.686105

In [17]:
val$b

[1] 0.07312717

In [18]:
other <- sapply(x,mean)
typeof(other)

[1] "double"

In [19]:
other
other[1]
other[2]

a          b 
2.68610463 0.07312717

a 
2.686105

b 
0.07312717

### Operations By Factors

Another widely used variant of the apply functions is the tapply function. The tapply function will take a list of data, usually a vector, a list of factors of the same list, and a function. It will then apply the function to each subset of the data that matches each of the factors.

In [20]:
val <- data.frame(a=c(1,2,10,20,5,50),
                    b=as.factor(c("a","a","b","b","a","b")))
val

a  b
1  1 a
2  2 a
3 10 b
4 20 b
5  5 a
6 50 b

In [21]:
result <- tapply(val$a,val$b,mean)
typeof(result)
result

[1] "double"

a         b 
 2.666667 26.666667

In [22]:
result[1]
result[2]

a 
2.666667

b 
26.66667

In [23]:
result <- tapply(val$a,val$b,summary)
typeof(result)
result

[1] "list"

$a
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   1.500   2.000   2.667   3.500   5.000 

$b
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.00   15.00   20.00   26.67   35.00   50.00 


In [24]:
result$a

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  1.000   1.500   2.000   2.667   3.500   5.000 

In [25]:
result$b

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  10.00   15.00   20.00   26.67   35.00   50.00 